version: "3.3"
    
services:
  db:
    image: mysql:latest
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    
  wordpress:
    depends_on:
      - db
    links: 
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: changeme
      VIRTUAL_HOST: changeme
      LETSENCRYPT_HOST: changeme
      VIRTUAL_PORT: 80

volumes:
  db_data:

networks:
  default:
    external:
      name: proxy-net