version: "3.3"
    
services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: wordpress
    
  wordpress:
    depends_on:
      - db
    links: 
      - db:mysql
    image: wordpress:latest
    restart: always
    volumes:
      - wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: changeme
      VIRTUAL_HOST: changeme
      LETSENCRYPT_HOST: changeme
      VIRTUAL_PORT: 80

volumes:
  db_data:
  wp-content:

networks:
  default:
    external:
      name: proxy-net